"""empty message

Revision ID: 5f95e58fd96a
Revises: 66c9b9d3fdc7
Create Date: 2023-09-29 01:42:16.163240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f95e58fd96a'
down_revision = '66c9b9d3fdc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('memo_month', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_detail', schema=None) as batch_op:
        batch_op.drop_column('memo_month')

    # ### end Alembic commands ###
