"""Add memo column to EmployeeDetail

Revision ID: 66c9b9d3fdc7
Revises: 6fa41b50b4a7
Create Date: 2023-09-28 23:35:15.208579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66c9b9d3fdc7'
down_revision = '6fa41b50b4a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('memo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_detail', schema=None) as batch_op:
        batch_op.drop_column('memo')

    # ### end Alembic commands ###
